package org.tywrapstudios.krafter.extensions.funtility

val ABBREVIATIONS = mutableMapOf(
	"rn" to "right now",
	"idk" to "i don't know",
	"btw" to "by the way",
	"imo" to "in my opinion",
	"imho" to "in my humble opinion",
	"brb" to "be right back",
	"omg" to "oh my god",
	"ttyl" to "talk to you later",
	"smh" to "shaking my head",
	"fyi" to "for your info",
	"tbh" to "to be honest",
	"lmk" to "let me know",
	"np" to "no problem",
	"yw" to "you're welcome",
	"gg" to "good game",
	"afk" to "away from keyboard",
	"bff" to "best friends forever",
	"wtf" to "what the fuck",
	"wth" to "what the hell",
	"rq" to "real quick",
	"srs" to "serious",
	"kys" to "keep yourself safe",
	"irl" to "in real life",
	"fym" to "the fuck you mean",
	"gtg" to "gotta go",
	"gn" to "good night",
	"gm" to "good morning",
	"wdym" to "what do you mean",
	"wb" to "welcome back",
	"lwk" to "low key",
	"stfu" to "shut the fuck up",
	"sybau" to "shut your bitch ass up",
	"sdiybt" to "start digging in yo butt, twin",
	"mf" to "motherfucker",
	"atp" to "at this point",
	"ty" to "thank you",
	"tysm" to "thank you so much",
	"ts" to "this",
	"gl" to "good luck",
	"jk" to "just kidding",
	"gf" to "girlfriend",
	"bf" to "boyfriend",
	"dm" to "direct message",
	"pm" to "private message",
	"tmi" to "too much information",
	"nvm" to "never mind",
	"ik" to "i know",
	"ikr" to "i know right",
	"idc" to "i don't care",
	"idfc" to "i don't fucking care",
	"idgaf" to "i don't give a fuck",
	"idek" to "i don't even know",
	"ngl" to "not gonna lie",
	"fr" to "for real",
	"frfr" to "for real for real",
	"ong" to "on god",
	"istg" to "i swear to god",
	"istfg" to "i swear to fucking god",
	"mb" to "my bad",
	"fs" to "for sure",
	"hmu" to "hit me up",
	"wya" to "where you at",
	"wbu" to "what about you",
	"hbu" to "how about you",
	"nm" to "not much",
	"nmu" to "not much you",
	"lmao" to "laughing my ass off",
	"lmfao" to "laughing my fucking ass off",
	"rofl" to "rolling on floor laughing",
	"rotfl" to "rolling on the floor laughing",
	"lmbo" to "laughing my butt off",
	"goat" to "greatest of all time",
	"og" to "original",
	"ggez" to "good game easy",
	"ggwp" to "good game well played",
	"wp" to "well played",
	"glhf" to "good luck have fun",
	"gg wp" to "good game well played",
	"op" to "overpowered",
	"pog" to "play of the game",
	"poggers" to "awesome",
	"gg no re" to "good game no rematch",

	"ttys" to "talk to you soon",
	"tty" to "talk to you",
	"cya" to "see you",
	"cyl" to "see you later",
	"cu" to "see you",
	"l8r" to "later",
	"l8" to "late",
	"m8" to "mate",
	"gr8" to "great",
	"h8" to "hate",
	"w8" to "wait",
	"b4" to "before",
	"2day" to "today",
	"2moro" to "tomorrow",
	"2nite" to "tonight",
	"thx" to "thanks",
	"thnx" to "thanks",
	"pls" to "please",
	"plz" to "please",
	"sry" to "sorry",
	"srry" to "sorry",
	"k" to "okay",
	"kk" to "okay",
	"ok" to "okay",
	"ihy" to "i hate you",
	"ily" to "i love you",
	"ilysm" to "i love you so much",
	"ilu" to "i love you",
	"imu" to "i miss you",
	"ru" to "are you",
	"u" to "you",
	"urs" to "yours",
	"tho" to "though",
	"thru" to "through",
	"cuz" to "because",
	"bc" to "because",
	"w/" to "with",
	"w/o" to "without",
	"b/c" to "because",
	"aka" to "also known as",
	"atm" to "at the moment",
	"rn" to "right now",
	"tn" to "tonight",
	"tmr" to "tomorrow",
	"tmrw" to "tomorrow",
	"yday" to "yesterday",
	"2day" to "today",
	"msg" to "message",
	"txt" to "text",
	"pic" to "picture",
	"pics" to "pictures",
	"vid" to "video",
	"vids" to "videos",
	"sec" to "second",
	"min" to "minute",
	"mins" to "minutes",
	"hrs" to "hours",
	"obv" to "obviously",
	"ofc" to "of course",
	"obvs" to "obviously",
	"prob" to "probably",
	"probs" to "probably",
	"def" to "definitely",
	"defs" to "definitely",
	"totes" to "totally",
	"yolo" to "you only live once",
	"bday" to "birthday",
	"gratz" to "congratulations",
	"grats" to "congratulations",
	"af" to "as fuck",
	"asf" to "as fuck",
	"smfh" to "shaking my fucking head",
	"smdh" to "shaking my damn head",
	"ffs" to "for fuck's sake",
	"omfg" to "oh my fucking god",
	"jfc" to "jesus fucking christ",
	"gtfo" to "get the fuck out",
	"stg" to "swear to god",
	"nbs" to "no bullshit",
	"tldr" to "too long didn't read",
	"eli5" to "explain like i'm five",
	"til" to "today i learned",
	"ama" to "ask me anything",
	"dae" to "does anyone else",
	"iama" to "i am a",
	"ftfy" to "fixed that for you",
	"imao" to "in my arrogant opinion",
	"ianal" to "i am not a lawyer",
	"iirc" to "if i recall correctly",
	"cmiiw" to "correct me if i'm wrong",
	"afaik" to "as far as i know",
	"ymmv" to "your mileage may vary",
	"itt" to "in this thread",
	"op" to "original poster",
	"nsfw" to "not safe for work",
	"nsfl" to "not safe for life",
	"sfw" to "safe for work",
	"tfw" to "that feeling when",
	"mfw" to "my face when",
	"mrw" to "my reaction when",
	"tbt" to "throwback thursday",
	"fbf" to "flashback friday",
	"mcm" to "man crush monday",
	"wcw" to "woman crush wednesday",
	"ootd" to "outfit of the day",
	"potd" to "photo of the day",
	"qotd" to "quote of the day",
	"motd" to "message of the day",
	"rotd" to "retweet of the day",
	"icymi" to "in case you missed it",
	"ftw" to "for the win",
	"lfg" to "let's fucking go",
	"gfg" to "go for gold",
	"fwiw" to "for what it's worth",
	"dw" to "don't worry",
	"dwbi" to "don't worry be happy",
	"ysk" to "you should know",
	"psa" to "public service announcement",
	"nbd" to "no big deal",
	"nw" to "no worries",
	"jsyk" to "just so you know",
	"jic" to "just in case",
	"bts" to "behind the scenes",
	"diy" to "do it yourself",
	"pov" to "point of view",
	"smth" to "something",
	"sth" to "something",
	"nth" to "nothing",
	"nthg" to "nothing",
	"ppl" to "people",
	"fav" to "favorite",
	"fave" to "favorite",
	"favs" to "favorites",
	"priv" to "private",
	"acc" to "account",
	"acct" to "account",
	"pfp" to "profile picture",
	"bio" to "biography",
	"notifs" to "notifications",
	"notif" to "notification",
	"convo" to "conversation",
	"convos" to "conversations",
	"collab" to "collaboration",
	"sesh" to "session",
	"diff" to "different",
	"dif" to "different",
	"tht" to "that",
	"thts" to "that's",
	"wht" to "what",
	"whts" to "what's",
	"wtv" to "whatever",
	"w/e" to "whatever",
	"wtvr" to "whatever",
	"nvr" to "never",
	"evr" to "ever",
	"4ever" to "forever",
	"2gether" to "together",
	"2gthr" to "together",
	"b/w" to "between",
	"btwn" to "between",
	"smwhr" to "somewhere",
	"smwhr" to "somewhere",
	"anywhr" to "anywhere",
	"nwhr" to "nowhere",
	"evry1" to "everyone",
	"every1" to "everyone",
	"sum1" to "someone",
	"some1" to "someone",
	"no1" to "no one",
	"any1" to "anyone",
	"ne1" to "anyone",
	"bout" to "about",
	"abt" to "about",
	"sposed" to "supposed",
	"sumthin" to "something",
	"nuthin" to "nothing",
	"sumwhere" to "somewhere",
	"str8" to "straight",
	"2moro" to "tomorrow",
	"2day" to "today",
	"2nite" to "tonight",
	"bb" to "baby",
	"bbg" to "baby girl",
	"bby" to "baby",
	"luv" to "love",
	"luvya" to "love you",
	"oc" to "original character",
	"dni" to "do not interact",
	"dfi" to "don't follow if",
	"byf" to "before you follow",
	"alt" to "alternate",
	"fb" to "follow back",
	"f4f" to "follow for follow",
	"l4l" to "like for like",
	"c4c" to "comment for comment",
	"s4s" to "shoutout for shoutout",
	"vod" to "video on demand",
	"y2k" to "year 2000 aesthetic",
)
